export const strings = {
    companyName: 'Twindix Global Inc.',
    login: {
        title: 'Login',
        welcome: 'Welcome back, please enter the details for your account',
        emailLabel: 'E-mail',
        emailPlaceholder: 'Enter E-mail here',
        passwordLabel: 'Password',
        passwordPlaceholder: 'Enter Password here',
        forgotPassword: 'Forget your password?',
        forgotPasswordLink: 'Click here',
        submitButton: 'Login',
    },
    authLayout: {
        welcomeTitle: 'Welcome Back to Twindix',
        welcomeDescription: 'Accurate recommendations for suitable academic and career paths, along with practical steps to help both the parent and the student make a confident, decisive choice.',
    },
    code: {
        titleEnter: 'Enter Code',
        titleSuffix: 'Job Bar to Display its',
        titleResult: 'Result',
        titleLoading: 'Loading...',
        titleIncorrect: 'Incorrect',
        titleCode: 'Code',
        inputPlaceholder: 'Enter code Job Bar here',
        buttonConfirm: 'Confirm',
        buttonLoading: 'Loading...',
        buttonReenter: 'Re-Enter',
        errorDefault: 'Re Enter the Code Again.',
        defaultUserName: 'User',
    },
    result: {
        copiedMessage: 'Copied to clipboard!',
        buttonReset: 'Reset',
        loading: 'Loading...',
    },
    profile: {
        title: 'Profile',
        nameLabel: 'Name',
        emailLabel: 'Email',
        userIdLabel: 'User ID',
        notAvailable: 'N/A',
    },
    common: {
        logout: 'Log out',
        loggingOut: 'Logging out...',
        loading: 'Loading...',
        language: 'EN',
        copy: 'Copy',
    },
    errors: {
        invalidExamCode: 'Invalid exam code',
        tryAgain: 'An error occurred. Please try again.',
        checkInput: 'Please check your input',
        invalidCredentials: 'Invalid credentials',
        examNotFound: 'Exam not found',
        processingFailed: 'Processing failed',
        jobNotFound: 'Job not found',
        invalidJobId: 'Invalid job ID',
        genericError: 'An error occurred',
    },
    validation: {
        emailRequired: 'Email is required',
        emailInvalid: 'Please enter a valid email address',
        passwordRequired: 'Password is required',
        passwordMinLength: 'Password must be at least 6 characters',
        passwordNeedsLetter: 'Password must contain at least one letter',
        passwordNeedsNumber: 'Password must contain at least one number',
        codeRequired: 'Please enter a code',
        codeMinLength: 'Code must be at least 3 characters',
    },
    forgotPassword: {
        title: 'Forgot Password',
        description: 'Enter your email address and we\'ll send you a link to reset your password.',
        emailLabel: 'Email Address',
        emailPlaceholder: 'Enter your email',
        submitButton: 'Send Reset Link',
        successMessage: 'If an account exists with this email, you will receive a password reset link.',
        backToLogin: 'Back to Login',
    },
    resetPassword: {
        title: 'Reset Password',
        description: 'Enter your new password below.',
        passwordLabel: 'New Password',
        passwordPlaceholder: 'Enter new password',
        confirmPasswordLabel: 'Confirm Password',
        confirmPasswordPlaceholder: 'Confirm new password',
        submitButton: 'Reset Password',
        successMessage: 'Your password has been reset successfully.',
        redirectMessage: 'Redirecting to login...',
        invalidLink: 'Invalid or expired reset link.',
        passwordMismatch: 'Passwords do not match.',
    },
} as const;
