export const strings = {
    login: {
        title: 'Login',
        welcome: 'Welcome back, please enter the details for your account',
        emailLabel: 'E-mail',
        emailPlaceholder: 'Enter E-mail here',
        passwordLabel: 'Password',
        passwordPlaceholder: 'Enter Password here',
        forgotPassword: 'Forget your password?',
        forgotPasswordLink: 'Click here',
        submitButton: 'Login',
    },
    authLayout: {
        welcomeTitle: 'Welcome Back to Twindix',
        welcomeDescription: 'Accurate recommendations for suitable academic and career paths, along with practical steps to help both the parent and the student make a confident, decisive choice.',
    },
    code: {
        titleEnter: 'Enter Code',
        titleSuffix: 'Job Bar to Display its',
        titleResult: 'Result',
        titleIncorrect: 'Incorrect',
        titleCode: 'Code',
        inputPlaceholder: 'Enter code Job Bar here',
        buttonConfirm: 'Confirm',
        buttonLoading: 'Loading...',
        buttonReenter: 'Re-Enter',
        errorDefault: 'Re Enter the Code Again.',
    },
    result: {
        copiedMessage: 'Copied to clipboard!',
        buttonReset: 'Reset',
        loading: 'Loading...',
    },
    profile: {
        title: 'Profile',
        nameLabel: 'Name',
        emailLabel: 'Email',
        userIdLabel: 'User ID',
        notAvailable: 'N/A',
    },
    common: {
        logout: 'Log out',
        loggingOut: 'Logging out...',
        language: 'EN',
        copy: 'Copy',
    },
    errors: {
        invalidExamCode: 'Invalid exam code',
        tryAgain: 'An error occurred. Please try again.',
    },
} as const;
